apiVersion: "v1"
kind: "Pod"
metadata:
  name: test-maven
  labels:
    jenkins: "slave"
    jenkins/label: "maven"
spec:
  initContainers:
  - name: initcontainer
    image: alpine:latest
    command: ['sh', '-c', 'chown 1000:1000 /home/jenkins/agent']
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
  containers:
  - image: "maven:3.9.0-eclipse-temurin-11"
    imagePullPolicy: "Always"
    name: "maven"
    command:
      - cat
    resources:
      limits: {}
      requests: {}
    tty: true
    volumeMounts:
    - mountPath: "/root/.m2"
      name: "maven-cache"
      readOnly: false
    # - mountPath: "/home/jenkins/agent"
    #   name: "workspace"
    #   readOnly: false
  restartPolicy: "Never"
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 2000
  volumes:
  - name: "maven-cache"
    persistentVolumeClaim:
      claimName: "nfs"
      readOnly: false
  # - name: "workspace"
  #   persistentVolumeClaim:
  #     claimName: "workspace"
  #     readOnly: false