apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    jenkins/label: "maven-ppc64le"
spec:
  containers:
  - env:
      - name: CURL_CA_BUNDLE
        value: /var/certs/ca-bundle.crt
      - name: JAVA_FIPS_OPTIONS
        value: "-Dcom.redhat.fips=false -Djavax.net.ssl.trustStore=/var/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    image: "image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven:latest"
    imagePullPolicy: "Always"
    name: "jnlp"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/.m2"
      name: "maven-cache"
      readOnly: false
    - mountPath: "/tmp"
      name: "source-code"
      readOnly: false
    - name: "volume-ca-bundle"
      mountPath: "/var/certs/"      
    - name: "volume-cacerts"
      mountPath: "/var/certs/java"     
    workingDir: "/tmp"
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  serviceAccountName: "jenkins-agent"
  volumes:
  - name: "maven-cache"
    persistentVolumeClaim:
      claimName: "maven-cache"
      readOnly: false
  - name: "source-code"
    persistentVolumeClaim:
      claimName: "source-code"
      readOnly: false
  - name: volume-ca-bundle
    configMap:
      name: ca-bundle
  - name: volume-cacerts
    configMap:
      name: java-keystore

# ${computer.jnlpmac} ${computer.name}