apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    jenkins/label: "maven"
spec:
  containers:
  - image: "maven"
    imagePullPolicy: "Always"
    name: "maven"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: true
    tty: true
  restartPolicy: "Never"