apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    jenkins/label: "buildah"
spec:
  containers:
  - args:
    - "9999999"
    command:
    - "sleep"
    image: "quay.io/buildah/stable:v1.23.1"
    imagePullPolicy: "IfNotPresent"
    name: "buildah"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/var/lib/containers"
      name: "container-layers-volume"
      readOnly: false
    - mountPath: "/tmp"
      name: "source-code-volume"
      readOnly: false
    workingDir: "/tmp"
  - image: "jenkins-agent-base:latest"
    imagePullPolicy: "Always"
    name: "jnlp"
    tty: false
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: "/var/lib/containers"
      name: "container-layers-volume"
      readOnly: false
    - mountPath: "/tmp"
      name: "source-code-volume"
      readOnly: false
    workingDir: "/tmp"
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  serviceAccountName: "jenkins"
  volumes:
  - name: "container-layers-volume"
    persistentVolumeClaim:
      claimName: "container-layers"
      readOnly: false
  - name: "source-code-volume"
    persistentVolumeClaim:
      claimName: "source-code"
      readOnly: false