apiVersion: "v1"
kind: "Pod"
spec:
  containers:
  - args:
    - "7d"
    command:
    - "sleep"
    image: "quay.io/buildah/stable:v1.23.1"
    imagePullPolicy: "Always"
    name: "buildah"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/var/lib/containers"
      name: "volume-0"
      readOnly: false
    - mountPath: "/tmp"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/tmp"
    image: "image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven:latest"
    imagePullPolicy: "Always"
  - name: "jnlp"
    resources:
      limits: {}
      requests: {}
    tty: false
    volumeMounts:
    - mountPath: "/var/lib/containers"
      name: "volume-0"
      readOnly: false
    - mountPath: "/tmp"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/tmp"
  hostNetwork: false
  securityContext:
    fsGroup: 1000650000
  serviceAccountName: "jenkins"
  volumes:
  - emptyDir:
      medium: ""
    name: "volume-0"
  - name: "workspace-volume"
    persistentVolumeClaim:
      claimName: "source-code"
      readOnly: false