apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    jenkins/label: "maven"
spec:
  containers:
  - image: "jenkins-agent-maven:latest"
    imagePullPolicy: "Always"
    name: "jnlp"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/.m2"
      name: "maven-cache"
      readOnly: false
    - mountPath: "/tmp"
      name: "source-code"
      readOnly: false  
    workingDir: "/tmp"
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  serviceAccountName: "jenkins-agent"
  volumes:
  - name: "maven-cache"
    persistentVolumeClaim:
      claimName: "maven-cache"
      readOnly: false
  - name: "source-code"
    persistentVolumeClaim:
      claimName: "source-code"
      readOnly: false