apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    jenkins/label: "maven"
spec:
  containers:
  - image: "maven:3.9.0-eclipse-temurin-11"
    imagePullPolicy: "Always"
    name: "maven"
    command:
      - cat
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: false
    tty: true
    volumeMounts:
    - mountPath: "/root/.m2"
      name: "maven-cache"
      readOnly: false
  restartPolicy: "Never"
  volumes:
  - name: "maven-cache"
    persistentVolumeClaim:
      claimName: "maven-cache"
      readOnly: false